#!/usr/bin/env bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

#Comenta la seccion de codigo que quieras deshabilitar 

#echo "Running branch name validation"
source $PROJECT_ROOT/.githooks/scripts/run-name_validation.sh

#echo "Running swiftlint hook.."
source $PROJECT_ROOT/.githooks/scripts/run-swiftlint.bash

#echo "Running unit tests"
source $PROJECT_ROOT/.githooks/scripts/run-tests.bash
