repos:
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.3.0
     hooks:
       - id: trailing-whitespace
       - id: check-json
       - id: trailing-whitespace
   - repo: https://github.com/realm/SwiftLint
     rev: 0.49.1
     hooks:
       - id: swiftlint
